CREATE DATABASE archiwum_db
WITH
    OWNER = postgres ENCODING = 'UTF8' LC_COLLATE = 'pl-PL' LC_CTYPE = 'pl-PL' LOCALE_PROVIDER = 'libc' TABLESPACE = pg_default CONNECTION
LIMIT = -1 IS_TEMPLATE = False;